---
ID: "e4c9c2d0-28ba-4c13-a081-97a6262be5f3"
Parent: "6ccba24c-6ea8-4064-afcd-fe0492cf486b"
Template: "4d50cdae-c2d9-4de8-b080-8f992bfb1b55"
Path: /sitecore/content/XMC Migration Collection/ESheba/Presentation/Headless Variants/ImageBanner/Default
BranchID: "4ca1885d-0445-4ac3-a1ab-97a15d5ae7ee"
SharedFields:
- ID: "dbbbeca1-21c7-4906-9dd2-493c1efa59a2"
  Hint: __Shared revision
  Value: "a968e0d0-d2f8-4a91-abc5-33c6e545757d"
- ID: "f6d8a61c-2f84-4401-bd24-52d2068172bc"
  Hint: __Originator
  Value: "{E050A0DC-56BB-4483-9B73-5A61BF2EDE12}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20251014T103925Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\darvi.sunny@tadigital.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\darvi.sunny@tadigital.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "8bc76735-7eee-4858-8b1e-0086d16de4dc"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\darvi.sunny@tadigital.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20251014T103925Z
